export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  ORDER_STATUS_INVALID: 'ORDER_STATUS_INVALID',
  STOCK_NOT_ENOUGH: 'STOCK_NOT_ENOUGH',
  PRODUCT_NOT_PURCHASED: 'PRODUCT_NOT_PURCHASED',
  ORDER_ALREADY_REVIEWED: 'ORDER_ALREADY_REVIEWED',
};
